// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXzQoSY5Oa0ZHrh0oTVX2t7vfLLXU6Eqs',
    appId: '1:773884376886:web:7524415a9667c5c89a2597',
    messagingSenderId: '773884376886',
    projectId: 'merambelediyesisiparis',
    authDomain: 'merambelediyesisiparis.firebaseapp.com',
    storageBucket: 'merambelediyesisiparis.firebasestorage.app',
    measurementId: 'G-RET4KLTZR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO8hUkV1KbyoKXfn3pmxbxDx-sEgvPoKs',
    appId: '1:773884376886:android:0cf42bf05e0783669a2597',
    messagingSenderId: '773884376886',
    projectId: 'merambelediyesisiparis',
    storageBucket: 'merambelediyesisiparis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGY6F0SJRG2q9-J0h708D3K6kaIKfVPjc',
    appId: '1:773884376886:ios:ad727530662a10be9a2597',
    messagingSenderId: '773884376886',
    projectId: 'merambelediyesisiparis',
    storageBucket: 'merambelediyesisiparis.firebasestorage.app',
    androidClientId: '773884376886-hl9gfpro1c70ib1nh19khdh07chgsefm.apps.googleusercontent.com',
    iosClientId: '773884376886-mn9j5ffdg1qeacj8d41osn7ra7hk4iic.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGY6F0SJRG2q9-J0h708D3K6kaIKfVPjc',
    appId: '1:773884376886:ios:ad727530662a10be9a2597',
    messagingSenderId: '773884376886',
    projectId: 'merambelediyesisiparis',
    storageBucket: 'merambelediyesisiparis.firebasestorage.app',
    androidClientId: '773884376886-hl9gfpro1c70ib1nh19khdh07chgsefm.apps.googleusercontent.com',
    iosClientId: '773884376886-mn9j5ffdg1qeacj8d41osn7ra7hk4iic.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXzQoSY5Oa0ZHrh0oTVX2t7vfLLXU6Eqs',
    appId: '1:773884376886:web:568d55c8f107317d9a2597',
    messagingSenderId: '773884376886',
    projectId: 'merambelediyesisiparis',
    authDomain: 'merambelediyesisiparis.firebaseapp.com',
    storageBucket: 'merambelediyesisiparis.firebasestorage.app',
    measurementId: 'G-L85HW6GZ0L',
  );
}
